services:
  loki:
    image: grafana/loki:latest
    command:
      -config.file=/etc/loki/local-config.yaml
    user: "10001:10001"
    ports:
      - 3100:3100
    networks:
      - internal
    volumes:
      - ${DATA_DIR:-./volumes}/loki:/var/lib/loki
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/var/lib/prometheus/data
    user: "65534:65534"
    ports:
      - 9090:9090
    networks:
      - internal
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - ${DATA_DIR:-./volumes}/prometheus:/var/lib/prometheus/data
    restart: unless-stopped
  tempo:
    image: grafana/tempo:latest
    command:
      - --config.file=/etc/tempo/tempo.yml
    user: "10001:10001"
    ports:
      - 3200:3200
      - 4317:4317
    networks:
      - internal
    volumes:
      - ./docker/tempo:/etc/tempo
      - ${DATA_DIR:-./volumes}/tempo:/var/lib/tempo
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    user: "472:472"
    environment:
      - PROMETHEUS_URL=${PROMETHEUS_URL:-http://prometheus:9090}
      - TEMPO_URL=${TEMPO_URL:-http://tempo:3200}
      - LOKI_URL=${LOKI_URL:-http://loki:3100}
    ports:
      - 3001:3000
    networks:
      - internal
      - dokploy-network
    volumes:
      - ${DATA_DIR:-./volumes}/grafana:/var/lib/grafana
      - ./docker/grafana:/etc/grafana/provisioning
    restart: unless-stopped
  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/config.yml
    networks:
      - internal
    volumes:
      - ./docker/promtail/config.yml:/etc/promtail/config.yml:ro
      - ${DATA_DIR:-./volumes}/promtail:/var/lib/promtail
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
networks:
  internal:
  dokploy-network:
    external: true