services:
  alloy:
    image: grafana/alloy:latest
    command: 
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - 12345:12345
    networks:
      - internal
    volumes:
      - ./volumes/alloy:/var/lib/alloy/data
      - ./docker/alloy/config.alloy:/etc/alloy/config.alloy
    restart: unless-stopped
  loki:
    image: grafana/loki:latest
    command:
      -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    networks:
      - internal
    volumes:
      - ./volumes/loki:/var/lib/loki
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/var/lib/prometheus/data
    ports:
      - 9090:9090
    networks:
      - internal
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - ./volumes/prometheus:/var/lib/prometheus/data
    restart: unless-stopped
  tempo:
    image: grafana/tempo:latest
    command:
      - --config.file=/etc/tempo/tempo.yml
    ports:
      - 3200:3200
      - 4317:4317
    networks:
      - internal
    volumes:
      - ./docker/tempo:/etc/tempo
      - ./volumes/tempo:/var/lib/tempo
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    environment:
      - PROMETHEUS_URL=${PROMETHEUS_URL:-http://prometheus:9090}
      - TEMPO_URL=${TEMPO_URL:-http://tempo:3200}
    ports:
      - 3000:3000
    networks:
      - internal
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./docker/grafana:/etc/grafana/provisioning
    restart: unless-stopped
networks:
  internal: