name: CI - Tests and Cache

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: miniapp_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up BEAM (Elixir/Erlang)
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.4'
          otp-version: '26.2.5.14'

      - name: Cache deps and build
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: mix-${{ runner.os }}-otp-26.2.5.14-elixir-1.18.4-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-${{ runner.os }}-otp-26.2.5.14-elixir-1.18.4-
            mix-${{ runner.os }}-

      - name: Install deps
        run: mix deps.get --only test

      - name: Compile
        run: mix compile

      - name: Run tests
        run: mix test



